# packages in environment at C:\Users\pdbrown\AppData\Local\Continuum\Anaconda3\envs\sap_aspen_query:
#
freetds                   1.00.9                    vc9_0  [vc9]
openssl                   1.0.2k                    vc9_0  [vc9]
pip                       9.0.1                    py27_1  
pymssql                   2.1.3                    py27_0  
python                    2.7.13                        0  
setuptools                27.2.0                   py27_1  
sqlalchemy                1.1.9                    py27_0  
vc                        9                             0  
vs2008_runtime            9.00.30729.5054               0  
wheel                     0.29.0                   py27_0  
xlsxwriter                0.9.6                    py27_0  
